# Setup
title:    The Sorna Project
tagline:  A distributed code snippet execution engine.
baseurl:  ""

# About/contact
author:
  name: Lablup Inc
  url:  http://www.lablup.com 

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
